// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5THrIOb5D1EOU9E9vfHgg4iIkMUONA0',
    appId: '1:504051441462:web:ed8dacb485dde885325d97',
    messagingSenderId: '504051441462',
    projectId: 'bookit-app-48d3b',
    authDomain: 'bookit-app-48d3b.firebaseapp.com',
    storageBucket: 'bookit-app-48d3b.firebasestorage.app',
    measurementId: 'G-TKHXNPK6Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdkrvdx1pSM8Fe1JB5ULjmWI04h_nqtdU',
    appId: '1:504051441462:android:e4af8616a2abae4d325d97',
    messagingSenderId: '504051441462',
    projectId: 'bookit-app-48d3b',
    storageBucket: 'bookit-app-48d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS5aQb8D9lZm4WJO44sfQ0vh5OeRhGpzY',
    appId: '1:504051441462:ios:3f4545d654227c96325d97',
    messagingSenderId: '504051441462',
    projectId: 'bookit-app-48d3b',
    storageBucket: 'bookit-app-48d3b.firebasestorage.app',
    iosBundleId: 'com.example.bookit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS5aQb8D9lZm4WJO44sfQ0vh5OeRhGpzY',
    appId: '1:504051441462:ios:3f4545d654227c96325d97',
    messagingSenderId: '504051441462',
    projectId: 'bookit-app-48d3b',
    storageBucket: 'bookit-app-48d3b.firebasestorage.app',
    iosBundleId: 'com.example.bookit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlV0Pu3vuubjhUPwifcn9MHQMyL4WVM_Y',
    appId: '1:504051441462:web:a35b861f97ec343b325d97',
    messagingSenderId: '504051441462',
    projectId: 'bookit-app-48d3b',
    authDomain: 'bookit-app-48d3b.firebaseapp.com',
    storageBucket: 'bookit-app-48d3b.firebasestorage.app',
    measurementId: 'G-FE2FPJFL79',
  );
}
